apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-agent-staging
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml

