apiVersion: v1
kind: Service
metadata:
  name: ai-coding-agent
  namespace: ai-agent-staging
  labels:
    app: ai-coding-agent
spec:
  selector:
    app: ai-coding-agent
  ports:
    - name: http
      port: 80
      targetPort: http

